openapi: 3.0.0
info:
  version: 1.0.0
  title: weather-api
  x-ibm-name: weather-api
servers:
  - url: /weather-api
x-ibm-configuration:
  properties:
    target-url:
      value: >-
        https://api.openweathermap.org/data/2.5/weather?&lat={lat}&lon={lon}&units=metric&appid=b6fecb886e634b5883d80acd8e536425
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          chunked-uploads: true
          persistent-connection: true
paths:
  /:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    parameters:
      - name: lat
        in: query
        description: Latitude coordinate
        required: true
        schema:
          type: number
          format: float
      - name: lon
        in: query
        description: Longitude coordinate
        required: true
        schema:
          type: number
          format: float
    put:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    post:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    delete:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    head:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
    patch:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: string
components:
  securitySchemes:
    clientID:
      type: apiKey
      in: header
      name: X-IBM-Client-Id
security:
  - clientID: []

